[package]
name = "godot-rust-rltk"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { git = "https://github.com/godot-rust/gdext", branch = "master" }
rand = "0.9.0"
rand_chacha = "0.9.0"
rand_pcg = "0.9.0"
